### ISSUE TITLE
If "attachment" property exists, the request fails at line 557 of rest-builder

### ISSUE THREAD

**Issue by br-kwon** [strongloop/loopback-connector-rest#126]
https://github.com/strongloop/loopback-connector-rest/blob/63bc8b7dd57ea9ac1e08cbee9b76f9676b3b8446/lib/rest-builder.js#L557

What is the variable 'r' supposed to be in this case? It is undefined at this point and is defined later as the invocation of this._request()

**Comment by virkt25** [comment]
`r` can be seen here: https://github.com/strongloop/loopback-connector-rest/blob/63bc8b7dd57ea9ac1e08cbee9b76f9676b3b8446/lib/rest-builder.js#L563

I think maybe it was supposed to be declared before we try using it. Would you like to submit a PR to address this issue?

**Comment by br-kwon** [comment]
Thanks @virkt25  I've submitted a pull request

**Comment by virkt25** [comment]
Thanks for the contribution @br-kwon! 🎉 💯 You change was landed and released in version 3.3.0. Is this issue good to close?

**Comment by br-kwon** [comment]
Great! yes you can close. thanks
