### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-connector-rest#133]
See comment https://github.com/strongloop/loopback-datasource-juggler/pull/1705#issuecomment-480254509

**Comment by emonddr** [comment]
![image](https://user-images.githubusercontent.com/6864736/55825072-3aa4f800-5ad3-11e9-9fe5-dfd89bac045a.png)

So this seems to be a throttling issue. We exceeded the "anonymous" tier limit.
We need to create an account for the team in the "first" tier (free) and integrate this API key into Travis CI build.
