### ISSUE TITLE
CRUD connected models do not pass filter parameter properly for all method

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [strongloop/loopback-connector-rest#136]
# Description/Steps to reproduce

1. Setup a repository binding a model to the rest connector with the crud flag
2. Try to call `repo.find` with a filter parameter
3. Observe that the filter parameter is passed to the remote server incorrectly and your filter is thus ignored

# Link to reproduction sandbox

https://github.com/mgabeler-lee-6rs/lb4-rest-filter

Repro steps for the sandbox app:
* `npm install`
* `npm start`
* Load http://localhost:3000/explorer/
* "Try out" the `rest-bug-demo` endpoint

The app:
* Sets up a model with a memory connector and a default CRUD controller
* Loads some example instances into the memory connector
* Sets up a REST connector & datasource for that model pointing at the CRUD controller
* Sets up a controller with a `POST` endpoint that will invoke `find` on the REST datasource with a query filter, and return the results

# Expected result

`GET` request is made to `/Model?filter...` instead of `/Model?where...` and thus only the requested objects are returned

# Actual result

All objects in the repository are returned regardless of filter.  Filter options like `include` and `fields` are ignored just like `where` is.

**Comment by mgabeler-lee-6rs** [comment]
This is closely related to https://github.com/strongloop/loopback-next/issues/2788

**Comment by mgabeler-lee-6rs** [comment]
`findById` and `findOne` are broken by the same issue.  It's possible to monkey-patch around the `find` and `findOne` bugs by overriding the methods and inserting the extra layer of `filter: {...}`, but the way `findById` is written, that trick doesn't work and monkey-patching around its bug requires a more complex solution.

**Comment by mgabeler-lee-6rs** [comment]
Actually, monkey-patching `findOne` is hard too

**Comment by mgabeler-lee-6rs** [comment]
Also finding that `404` handling for even a basic `findById` (which does issue the correct REST request) is broken -- it returns the HTTP exception, fails to translate it into an `EntityNotFoundError`

**Comment by mukunzidd** [comment]
@mgabeler-lee-6rs  for me this error has stopped the project build process and only when I remove the block which contains the `.find` call... only then the project can run. Even, I was trying this in the Todo and the TodoList examples in the official doc. Even in any new project that I start 0and generate a CRUD controller, as well as your demo for this issue. I am currently using `@loopback/core: "^1.7.1"`, I wanted to try using Loopback in my upcoming project but I can't get past this... Any thoughts?

**Comment by mgabeler-lee-6rs** [comment]
Here's a gist with a slightly simplified version of my monkey patching:
https://gist.github.com/mgabeler-lee-6rs/6f30a3e117182060cc88a8d20e6ed914

The idea is that you extend this base class instead of the normal one that it extends when creating a repository that uses a rest datasource under the hood.  And _only_ when it's using rest under the hood -- this will almost certainly break things if you use any other datasource.

I would caution if you adopt something like this in your own code base to write _very careful_ acceptance tests, and not to assume any methods not "fixed" are working unless you have such tests that prove it.  Speaking from experience, it is _very_ easy to make mistakes in the acceptance tests and think you have patched the methods correctly when you have not.

**Comment by bajtos** [comment]
@raymondfeng PTAL

**Comment by mgabeler-lee-6rs** [comment]
still broken as described

**Comment by mgabeler-lee-6rs** [comment]
![image](https://user-images.githubusercontent.com/41014492/69065403-b5c97780-09ed-11ea-885b-ed30234ac447.png)
