### ISSUE TITLE
The parameter named timestamp was changed as ×tamp while invoking remote methods

### ISSUE THREAD

**Issue by xinshouke** [strongloop/loopback-connector-rest#19]
I defined a remote method ,there are four accepts parameters in remote methods, but I call the method in loopback explorer, the Request URL  looks like with some problems like below:
http://112.124.3.162:3000/api/weixins/ansWeixintoken?signature=1×tamp=2&nonce=3&echostrcb=4
the parameter named timestamp was changed as ×tamp without &.....
------------------------------------------the remote method defining---------------------------------------------
obj.ansWeixintoken = function(signature, timestamp,nonce,echostrcb,cb) { ....}
obj.remoteMethod(
        'ansWeixintoken',
        {    
          accepts: [{arg: 'signature', type: 'string'},
            {arg: 'timestamp', type: 'Date'},
            {arg: 'nonce', type: 'string'},
            {arg: 'echostrcb', type: 'string'}],
          // returns: {arg: 'greeting', type: 'string'},
          returns: {arg: 'Weixin', root: true},
          http: {path: '/ansWeixintoken', verb: 'get'}
        }
    );

--------------------------------------------screen shut--------------------------------------------------------

![rest](https://cloud.githubusercontent.com/assets/3468107/4749124/5d84301a-5a7f-11e4-8d83-7e00216812a0.jpg)

**Comment by richardpringle** [comment]
@xinshouke.... that is really weird. Sorry about the huge delay in response time but this issue is actually in the wrong repository. It belongs in [LoopBack](https://github.com/strongloop/loopback) instead. If it is still relevant, please re-open there.

**Comment by richardpringle** [comment]
Also mention me in a comment or the description if you do decide to re-open so I can help you out!
