### ISSUE TITLE
Support http.source configuration in datasources.json templates.

### ISSUE THREAD

**Issue by ctotheameron** [strongloop/loopback-connector-rest#20]
Currently when reading the operations[template] from datasources.json, rest-connector.js hardcodes the source value to "query". I have many use-cases where I would like to configure the source value of my params without having to write custom code. 

See:
https://github.com/strongloop/loopback-connector-rest/blob/master/lib/rest-connector.js#L56

My proposal would be to extend the variable definition syntax to include param source. Something like:
'{x=100:number#path}'

Happy to take a crack at this and submit a PR if you think it's worth implementing.

**Comment by mayur-arora** [comment]
How do I set dynamic / custom headers in the data source file ? I've observed, they work only if if put them in the data source file.

**Comment by richardpringle** [comment]
@aroramayur, please ask your question in one of the following locations:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

Hopefully you will actually get an answer when you post in there :smiley:.

@ctotheameron, I assume that you have figured this out from your last comment. I will now close the issue but please feel free to re-open if need be (just make sure your mention me in a comment so I can tend to it right away).
