### ISSUE TITLE
delete api not working

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-connector-rest#21]
I seem to have a problem with the delete api

if I use the strongloop api with  a DELETE (from either explorer or curl) to 

    http://myStrongLoopServer/api/configs/f574ecc8-d217-1788-ed13-280678d73209

the server crashes with 
    TypeError: object is not a function
        at /home/myapp/loopback/node_modules/loopback-connector-rest/lib/rest-connector.js:246:9

I think that my backend rest server is only getting the /configs url

    executing request: DELETE || controllers/configs path: /Service=configs

however,if I use postman or curl to send a DELETE directly to the backend server, the path is

    executing request: DELETE || controllers/configs path: /Service=codeGloo/configs/f574ecc8-d217-1788-ed13-280678d73209

ie the id is attached

thanks

**Comment by jmls** [comment]
is this being fixed in #406  ? (https://github.com/strongloop/loopback-datasource-juggler/pull/406)

**Comment by davidrgarza** [comment]
In light of https://github.com/strongloop/loopback-datasource-juggler/pull/403 the current way that the rest connector implements deleteAll is incompatible, causing an issue when attempting to deleteByid.

**Comment by jouke** [comment]
I ran into the same issue last night. As it turns out, dao.js always calls destroyAll with either 4 or 3 parameters. loopback-connector-rest however accepts only two (model and callback). In between those two *should* be the 'where' parameter. So destroyAll gets the where parameter where it expects the callback, causing the `TypeError: object is not a function` when calling the callback.

My workaround is a replacement of destroyAll which I implemented as follows:
```
  // Apparently there is a bug in the loopback-connector-rest. destroyAll is called
  // from dao.js, with a 'where' parameter, but the connector does not pick up on that
  // parameter and expects only a callback as second parameter. This fixes it
  connector.destroyAll = function destroyAll(model, where, callback) {
    if (where && where.id) {
      connector.getResource(model).delete(where.id, connector.responseHandler(model, callback));
    }
    else {
      connector.getResource(model).deleteAll(connector.responseHandler(model, callback));
    }
  };
```

**Comment by jmls** [comment]
wow! it's only been 18 months since this major bug has been raised, with no fix ... ;) Many many thanks for the workaround.

Where would I put this code ?

thanks

**Comment by jouke** [comment]
I have put it in a boot script, and got the reference to the connector by doing this:

```
var model = 'customer';  //or whatever the name of any of your REST-connector-based model is
var connector = app.models[model].getDataSource().connector;
```
So if you put this right in front of the code I posted before, and save it in a boot script, it should work

**Comment by jmls** [comment]
excellent. thanks

**Comment by radinaladesudiarsa** [comment]
how to extended
 api delete  in model.js
