### ISSUE TITLE
Models that attached to a rest connector doesn't mixin Relation and Inclusion

### ISSUE THREAD

**Issue by clarkorz** [strongloop/loopback-connector-rest#24]
Rest connector define an new `DataAccessObject`[(related line)](https://github.com/strongloop/loopback-connector-rest/blob/master/lib/rest-connector.js#L19) which doesn't minin `Relation` and `Inclusion`. 

if a model is defined with relations or scopes,  and attached to a rest connector, it will fail the startup.

**Comment by richardpringle** [comment]
@clarkorz, the rest connector is meant to be used as a service. You create a datasource that connects to a 3rd party rest api to make proxy calls to that api. You **should not** connect any models to this connector. 

Does that make sense? 

If there are any specific places in the documentation that could clear this up, please open a new issue and mention me in a comment or in the description and I will tend to it as soon as possible.
