### ISSUE TITLE
Can't transfer images/binary data

### ISSUE THREAD

**Issue by muehle28** [strongloop/loopback-connector-rest#26]
If I connect to a restservice http://path.com/imgfile.png and change the mime type in the before hook to image/png the image file is broken.
Is it possible to transfer binary data or pipe a request?

**Comment by mustaine** [comment]
I am also interested in it

**Comment by ainesophaur** [comment]
I'd also like the ability to pipe my request inside of the REST data source. I use the REST connector datasource as a wrapper to forward off to some internal routes. I'd like to be able to pipe the http incoming request response to the REST connector instead of providing a callback.

**Comment by richardpringle** [comment]
I wouldn't be surprised if there was some kind of workaround to accomplish this but it would also be a good feature to have out of the box. I'll throw a feature label on this issue so that it can enter our backlog.

If any of you figure out a way to do this yourself, it is highly encouraged that you submit a PR to improve the module!

**Comment by tco** [comment]
@muehle28, @mustaine and @ainesophaur if this is still an issue for you, I found a way to circle around this problem.
consider models/file.js:

```JavaScript
var request = require('request');

module.exports = function(File) {
    File.download = function(response, cb) {
        request('http://example.tld/path/to/file').pipe(response);
    };

    File.remoteMethod(
        'download',
        {
            accepts: [{ arg: 'res', type: 'object', 'http': { source: 'res' } }],
            returns: {},
            http: {verb: 'get'}
        }
    );
};

```

**Comment by peeyushKriplani** [comment]
I am also facing same issue i am upload image on owncloud one code which is working fine in restler but not working in loopback.
