### ISSUE TITLE
Best practice on passing through oAuth details

### ISSUE THREAD

**Issue by simonguest** [strongloop/loopback-connector-rest#32]
I have created a connection to an existing API using the REST connector, which is working well. I would however like to pass through the oAuth token coming from the client to the server.

I can get hold of the oAuth token by grabbing ctx.req.headers.authorization from the Model.beforeRemote method, but can't seem to figure out a way of passing it to the REST connector as a new header.

I've tried a couple of things:

Adding a hook using Model.observe (but this doesn't seem to fire with the REST connector).

Using a template with an authorization field - but have not been able to get this working correctly.

Any ideas appreciated.

**Comment by raymondfeng** [comment]
You probably need to do two things:

1. Set the authorization header as a variable for the REST template so that you have an accessToken parameter
2. Use http://docs.strongloop.com/display/LB/Using+current+context <http://docs.strongloop.com/display/LB/Using+current+context> to retrieve the current req.headers.authorization (or you can write a custom method to receive the authorization header as an argument).

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by simonguest** [comment]
Thanks for the prompt reply, Raymond - I think I'm pretty close. I have setup a template in datasources.json that looks as follows:

```
"connect": {
    "name": "connect",
    "connector": "rest",
    "debug": "true",
    "operations": [
      {
        "template": {
          "method": "GET",
          "url": "http://internalserver/api/reports",
          "headers":{
            "authorization": "OAuth {token}"
          }
        },
        "functions": {
          "find": []
        }
      }
    ]
  }
```

And my report.js model is as follows:

```
module.exports = function(Report) {
  Report.beforeRemote('find', function(ctx, report, next){
    ctx.token = ctx.req.headers.authorization;
    console.log(ctx.token);
    next();
  });
};
```

The final piece of the puzzle (that I'm missing) is how I pass the token in context as a parameter to the rest connector. Any ideas?

**Comment by canercandan** [comment]
Hey @simonguest,

I am struggling with this problem as well trying to figure out how to authenticate efficiently to another external API using oauth/oauth2. Did you find any solutions so far ?

Thanks.

**Comment by simonguest** [comment]
Yes @canercandan , I was able to figure this out.

- Configure the datasources.json file as shown at the start of this thread, however also include the token in the function. For example:

```
"functions": {
          "get": ["token"]
        }
```
- Ensure that the token is accessible in the beforeRemote method (also shown at start of thread)
- To pass the token, add a req argument in your remote method, with source of "req". For example:

```
Model.remoteMethod(
    'call',
    {
      http: {path: '/', verb: 'get'},
      accepts: [
        {arg: 'req', type: 'object', http: {source: 'req'}}
      ],
      returns: {
        root: true
      }
    }
  );
```

- Finally, in the remote method itself, pass the req.token when you make the call:

```
Model.call = function (req, cb) {
    Model.get(req.token, function (err, instance) {
      cb(null, instance);
    });
  };
```

That should be enough to pass through the auth token to an internal endpoint.

Hope this helps!

**Comment by simonguest** [comment]
Closing issue as this is now resolved.

**Comment by cojack** [comment]
Guys, it's not resolved at all, you will override all the functions to add token to each CRUD operation?

**Comment by jmls** [comment]
@cojack did you ever get a solution that worked for you ? Same problem here ;)

**Comment by cojack** [comment]
@jmls nope. I stuck with passing everywhere access token, it's horrible :-1:
