### ISSUE TITLE
How to access response status code

### ISSUE THREAD

**Issue by mrfelton** [strongloop/loopback-connector-rest#34]
Hi,

In previous versions of this module, requests used to return an array containing 2 items. The first item would contain the response body. The second item would contain the full response data. This made it possible to fully inspect the result and act accordingly.

In the latest version this behaviour appears to have changed somewhat. Now, requests only ever return a single argument which is the response body. What is the recommended way of inspecting the rest of the response in order to get information about the status code or other properties?

**Comment by mrfelton** [comment]
To clarify - this appears to be an issue when using native promise support that I thought had been added this module recently in the same way as it has been throughout the loopback codebase.

**Comment by jdrouet** [comment]
@mrfelton actually, if you call a function defined in your datasource in your model, the callback contains 3 parameters :
- an error if exists
- the response body
- the response of the datasource call

So you can find it like this :
    ```javascript
    function(err, body, res) {
     console.log('status code', res.statusCode);
    }
    ```

**Comment by mrfelton** [comment]
@jdrouet thanks, I understand that. However if you try calling one of the rest endpoint methods using the promise style both return parameters are not available. For example:

```javascript
Model.someMethod(arg1, arg2)
  .then(function(body, res) {
    console.log(body);
    console.log(res);
  })

`res` is not set in this case.

See https://github.com/strongloop/loopback/issues/418 for details and context about promise support that was recently added to loopback.

The only way to use this style of coding with the rest connector currently is to manually Promisify the model.

**Comment by richardpringle** [comment]
closing in favor of #60
