### ISSUE TITLE
POST'ing to an embedsMany relationship within a REST model generates a 405 error

### ISSUE THREAD

**Issue by joncarlson** [strongloop/loopback-connector-rest#35]
For example, say I have a REST model named **Person** and it has an embedsMany relationship to a PersistedModel named **Pet** like so:

```
"relations": {
    "pets": {
      "type": "embedsMany",
      "model": "Pet",
      "foreignKey": "",
      "property": "pets"
    }
}
```

If I try to create a new pet, using `POST /person/1/pets/` I get a 405 method not allowed error back

**Comment by richardpringle** [comment]
@joncarlson, sorry but this is actually in the wrong repo. If it is still an issue, please open in [LoopBack](https://github.com/strongloop/loopback).

Sorry about the delayed response and the confusion!

**Comment by richardpringle** [comment]
You can mention me in the new issue to get a faster response too if you decide to open one.
