### ISSUE TITLE
Unable to extract body content from client request?

### ISSUE THREAD

**Issue by DesktopMan** [strongloop/loopback-connector-rest#36]
lb-services.js:

```
"func": {
  url: urlBase + "/func",
  method: "POST"
}
```

datasources.json:

```
"template": {
  "method": "POST",
  "url": "http://some.domain/func",
  "headers": {
    "accepts": "application/json",
    "content-type": "application/json"
  },
  "body": {
    "var1": "{var1}",
    "var2": "{var2}"
  }
},
"functions": {
  "func": [
    "var1",
    "var2"
  ]
}
```

If I post

```
{ "var1": "1", "var2": "2" }
```

the outgoing request to some.domain sends the body with var1 and var2 set to null. Am I doing something wrong?

**Comment by raymondfeng** [comment]
By default, the arguments are mapped to query parameters.

**Comment by DesktopMan** [comment]
How would I change them to get it working? I've looked at the examples and
the documentation but couldn't find much about POST.

**Comment by raymondfeng** [comment]
Have you tried `func({var1: "1", var2: "2"})` from Angular?

**Comment by DesktopMan** [comment]
I can see that the client request is correct: A POST with the object you
describe, but it's not picking up the variables in the object for some
reason. Have I set it up correctly? What did you mean by "By default, the
arguments are mapped to query parameters."?

**Comment by raymondfeng** [comment]
The client should send an HTTP request to `/api/<your-model>/func?var1=1&var2=2`.

**Comment by DesktopMan** [comment]
ah I see what you're saying. Are there any plans to support incoming POST?
I run into URL length issues with GET, and it also makes it harder to see
the request parameters while debugging (URL-encoded and what not).

**Comment by evseevnn** [comment]
i have this problem too.
implementation support incoming POST is real?

**Comment by superkhau** [comment]
@evseevnn Would you like to submit a patch?

**Comment by evseevnn** [comment]
Yes, i just want more transparent proxying requests to the api. 
If i have rest endpoint with POST method for proxying, i want have possible to send parameters in body of POST request but no in query string

**Comment by SuhasUnited90** [comment]
Any idea when this capability will be added...I am waiting for the same ..

**Comment by superkhau** [comment]
Esclating to feature request.

**Comment by GustavoRPS** [comment]
+1

**Comment by lunow** [comment]
+1
