### ISSUE TITLE
Json value is set to null if not supplied

### ISSUE THREAD

**Issue by DesktopMan** [strongloop/loopback-connector-rest#37]
```
      {
        "template": {
          "method": "GET",
          "url": "http://some.domain/func",
          "body": {
		    "value1": ""{value1=5}",
            "value2": "{value2:json}"
          }
        },
        "functions": {
          "func": [
            "value1",
            "value2",
          ]
        }
      }
```

value2 is set to null in the body if it's not supplied in the client request. Shouldn't it simply be omitted?

I also tried giving it a default:

```
"value2": "{value2=[]:json}"
```

However, the default becomes "[]" as a string and not an empty json array.

**Comment by DesktopMan** [comment]
Any update on this? Both omitting and setting default values for JSON parameters would be very useful...

**Comment by raymondfeng** [comment]
For json type, we can try to run JSON.parse for the default. 

To omit a property, can you try to set the value to `undefined`?

**Comment by DesktopMan** [comment]
Running JSON.parse for the default would be great. It would solve several of my issues if default values for JSON was parsed as JSON. I'll try undefined for omission, thanks for the tip :)

**Comment by raymondfeng** [comment]
Please try 1.10.0.
