### ISSUE TITLE
Support for APIs that return data in XML format

### ISSUE THREAD

**Issue by mrfelton** [strongloop/loopback-connector-rest#38]
Currently, the application crashes with a fatal error if the remote API returns data in a non-json format (xml for example). It should support XML data, and convert it to JSON similar to https://github.com/strongloop/loopback-connector-soap

**Comment by royklopper** [comment]
:+1:  I'm looking for the same thing, but our remote resource also only accepts XML input. I saw some of your commits in your fork, could you explain how your solution works, maybe we could pick this up together?
