### ISSUE TITLE
Document the resourceName model property

### ISSUE THREAD

**Issue by mrfelton** [strongloop/loopback-connector-rest#39]
After some reverse engineering I was able to figure out that it's possible to explicitly control the remote URL when using CRUD functionality by setting the `resourceName` property on a model definition. This allows for a local model name that is different from the remote resource name.

For example,

```
var config = {
  "name": "ServiceTransaction",
  "base": "PersistedModel",
  "resourceName": "transactions"
}

var ServiceTransaction = ds.createModel('ServiceTransaction', {}, config);
```

With this I have a resource model named ServiceTransaction, but whose crud urls call out to `baseUrl + '/transactions'`

Without setting `resourceName` the calls would have been made to `baseUrl + '/ServiceTransaction'`.

It would be good to have this documented!

**Comment by antoineverger** [comment]
Good to know that. It needs to be documented.

**Comment by crandmck** [comment]
I added https://docs.strongloop.com/display/LB/REST+connector#RESTconnector-SettingtheresourceURL.

@mrfelton @antoineverger Please take a look.

**Comment by antoineverger** [comment]
Great ! Thanks @crandmck , it will help a lot newbies ;)

**Comment by bajtos** [comment]
> I added https://docs.strongloop.com/display/LB/REST+connector#RESTconnector-SettingtheresourceURL.

@raymondfeng ping, could you please check the updated docs so that we can close this issue?

**Comment by jonathanwoahn** [comment]
Does this still work?

**Comment by bajtos** [comment]
@jonathanwoahn if the `resourceName` property does not work for you, then please open a new issue and provide a sample project reproducing the problem, see our [bug reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report).
