### ISSUE TITLE
REST connector for LoopBack REST services as a datasource

### ISSUE THREAD

**Issue by voitau** [strongloop/loopback-connector-rest#40]
There are two LoopBackJS applications: AppA and AppB. AppB has ModelX. AppA also needs to configure ModelX, which is the same as a model on AppB, and use AppB as a datasource via REST connector. Is there any example of using LoopBack REST services as a data source via REST connector? Which includes passing all parameters like "filter" with "include", "limit", etc.

I tried to do a basic setup. I checked only `find` method, which works for a default query. However, passing parameters in a usual way does not work. E.g., if this query `filter={"include":"items", "limit":2}` works for  AppB, it does not affect the response if passed as a parameter to AppA. However, based on some debugging, such syntax makes a proper query: `filter={"filter":{"include":"items", "limit":2}}` and limits results, although relation is not expanded.

**Comment by voitau** [comment]
Hi, any news here? Thanks!

**Comment by raymondfeng** [comment]
Have you checked out http://docs.strongloop.com/display/public/LB/Remote+connector?

**Comment by voitau** [comment]
@raymondfeng, yes, it looks like what's necessary. Thanks.

**Comment by crandmck** [comment]
I believe this issue can be closed as the OP's request is met.
