### ISSUE TITLE
statusCode on error from looopback is not correct

### ISSUE THREAD

**Issue by prashantbaid** [strongloop/loopback-connector-rest#41]
I am making an API call to a commerce system (Hybris) using rest-connector in loopback. When there is an error, i am getting response statusCode as 200, whereas the error statusCode sent from hybris is 4xx. Also, when I hit the same URL from my browser (Chrome), I am getting statusCode 4xx. Why is loopback converting the statusCode to 200 and how do I get the original statusCode?

I also asked this question on loopbackJS google group- 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/loopbackjs/Wkj3Gz3wWJA/dhYAHUPICwAJ

**Comment by horiaradu** [comment]
If you use promises, then you can't get the status code. Your code most likely looks like this:

```
Model.find(params)
.then(function(data) {})
.catch(function(err) {})
```

In order to work around this, I supplied a callback with 3 parameters (error, data and response object) and interpreted the status code:

```
function promisifyRestCall(restCall, args) {
  return new global.Promise(function (resolve, reject) {
    restCall.apply(this, args.concat(function (err, data, response) {
      if (err) {
        reject(err);
      } else if (response.statusCode >= 400) {
        reject(data);
      } else {
        resolve(data);
      }
    }));
  });
}
```

and in the caller code, I do:

```
promisifyRestCall(Model.find, [params])
.then(function(data) {})
.catch(function(err) {})
```

**Comment by richardpringle** [comment]
Took a look at the code and also tested it out and it looks like this has been fixed. Please re-open if the issue persists.

Didn't look in too much detail, but I see @horiaradu made some contributions... thanks!
