### ISSUE TITLE
Default template values are not passed to the builder operations

### ISSUE THREAD

**Issue by aaafly** [strongloop/loopback-connector-rest#42]
When setting a default value:

``` javascript
{name=defaultValue:type}
```

The default value is not set in the builder

``` javascript
// rest-connector.js line 58
fn.accepts.push({
  arg: p,
  type: args[p].type,
  required: args[p].required,
  http: {source: 'query'}
});
```

This result in swagger not having the data and not setting the input with the default value.

_note: i'm willing to fix and create a test for it_

**Comment by richardpringle** [comment]
@aaafly, please fix! Mention me in the PR and I'll make sure it gets reviewed!
