### ISSUE TITLE
How do I use RequestBuilder ?

### ISSUE THREAD

**Issue by joneqian** [strongloop/loopback-connector-rest#46]
Has RequestBuilder been abandoned in the latest version?
How do I use RequestBuilder ?

Thanks!!

**Comment by richardpringle** [comment]
@joneqian, I'm not sure what you mean? You can see in the latest code that `RequestBuilder` refers to the `rest-builder.js` file:
https://github.com/strongloop/loopback-connector-rest/blob/dab5a1ddf9d17c8648380566d30d2a38804a62af/lib/rest-connector.js#L8

Also, for further questions, please ask in one of the following locations:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

We're reserving the GitHub issues section for feature requests and bug reports only. I am going to close the issue for now, but feel free to carry on the discussion in here. If we need to, we can always open a new doc issue if something is unclear.
