### ISSUE TITLE
http source hardcoded to 'query'.

### ISSUE THREAD

**Issue by sachinhub** [strongloop/loopback-connector-rest#50]
For the custom methods created from the template, it is not possible to expose a POST method which can accept data as request body. This is because of following lines in rest-connector.js where http source is hard-coded to be 'query'

```
            fn.accepts.push({arg: p, type: args[p].type,
              required: args[p].required, http: {source: 'query'}});
          });
```

As a temporary solution, I have forked the repo and made following change in it -

```
              // Temporary fix- Sachin Mane.
            var source = args[p].type === 'object' ? 'body' :'query';
            fn.accepts.push({arg: p, type: args[p].type,
              required: args[p].required, http: {source: source}});
          });
```
That means if the type of the parameter is object, it will be accepted as a request body instead of a query string parameter.

I am not sure about the permanent fix to above problem unless we add additional config in the template. 

Any suggestions?

**Comment by richardpringle** [comment]
Looks like this was fixed! If I'm wrong, please re-open and mention me in a comment.
