### ISSUE TITLE
Loopback current context getting lost when model makes a rest call through rest connector

### ISSUE THREAD

**Issue by itsJyo** [strongloop/loopback-connector-rest#59]
When a model connected to loopback rest connector makes a rest call the loopback current context becomes null.

Steps to reproduce the issue:

1.Clone the forked repo  https://github.com/itsJyo/loopback-sandbox
2.Start the app
3.Call the remote method "getRemoteCustomer" on the Customer model.(use explorer)
4.Check the corresponding logs on the customer.js file (model js file)

**Comment by richardpringle** [comment]
Hey @itsJyo, thanks for forking the sandbox, makes my life so much easier! Next time, it would be even better if you could update the package.json, however, I can't really complain as the sandbox is a lot further than the average user goes anyway ;).

Only thing is... I couldn't reproduce the issue. The `ctx` was the same before and after the request.

Any ideas?

What does the console output look like in your case?

**Comment by itsJyo** [comment]
Hey @richardpringle , i missed to update the package.json. will make sure next time. :-)

The ctx i get before and after the request is as below:

current Context Before Rest : Namespace {
  name: 'loopback',
  active: { accessToken: undefined, tenantid: 'ev' },
  _set: [ null ],
  id:
   AsyncListener {
     create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }

current Context After Rest : Namespace {
  name: 'loopback',
  active: null,
  _set: [],
  id:
   AsyncListener {
     create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }

notice the active object of ctx.

**Comment by itsJyo** [comment]
@richardpringle i have added another model Employee(connected to memory db) and added a remote method "createEmployee" in which i am creating employee model instance.

i have logged the current context before and after the create api. ctx.active remains same which is as expected.
i was expecting the same behavior in Customer model(connected to rest data source) as well.

**Comment by raghav135** [comment]
+1

**Comment by richardpringle** [comment]
Steps:
- cloned your repo
- cd into sandbox folder and ran `node .`
- open `localhost:3000/explorer` 
- click `Try it out!` at `GET /Employees/createEmployee`
- click `Try it out!` at `POST /Customers/getRemoteCustomer`

and here is my output.

```shell
current Context Before Create : Namespace {
  name: 'loopback',
  active: { accessToken: undefined, tenantid: 'ev' },
  _set: [ null ],
  id:
   AsyncListener {
     create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }
current Context after create : Namespace {
  name: 'loopback',
  active: { accessToken: undefined, tenantid: 'ev' },
  _set: [ null ],
  id:
   AsyncListener {
     create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }
current Context Before Rest : Namespace {
  name: 'loopback',
  active: { accessToken: undefined, tenantid: 'ev' },
  _set: [ null ],
  id:
   AsyncListener {
     create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }
{}
current Context After Rest : Namespace {
  name: 'loopback',
  active: { accessToken: undefined, tenantid: 'ev' },
  _set: [ null ],
  id:
   AsyncListener {
     create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }
```

is there something more that I should be doing to reproduce?

**Comment by raghav135** [comment]
Able to simulate with node LTS on windows. I am using latest npm (not the one which comes with node LTS). Consistently simulatable.
Can you try few times and see if this issue occurs in one of the attempts?
May I know your env please.

**Comment by richardpringle** [comment]
Node 4.3.1
NPM 2.15.1

Will try with node 4.4.4

**Comment by richardpringle** [comment]
and I'm on windows

**Comment by richardpringle** [comment]
Tried it out on 4.4.4 and got the same result. I'll get someone to try it out on a mac.

@gunjpan, could you take a look at this? Just need to clone [this sandbox fork](https://github.com/itsJyo/loopback-sandbox) and follow the steps in [this comment](https://github.com/strongloop/loopback-connector-rest/issues/59#issuecomment-217466507)

Thanks!

**Comment by gunjpan** [comment]
@rpring, @itsJyo : Hey, I tried cloning the sandbox and running the app as per the steps in the comments and found it working fine.

**Comment by itsJyo** [comment]
i m using
Node 4.2.4
npm 3.5.2
and able to reproduce it..

let me try it with node 4.4.4

**Comment by itsJyo** [comment]
Tried with node 4.4.4 and npm 3.5.2 on windows. Able to reproduce the issue consistently.

**Comment by richardpringle** [comment]
@itsJyo, do you have any other systems you could try this on (or get a friend to try)? We've tried to reproduce on a couple different platforms and we weren't seeing the same issue. Seems to me like it might be your machine/environment. Not quite sure how else we could move forward.

Let me know

**Comment by itsJyo** [comment]
@richardpringle , I have already got my colleagues try it and was able to reproduce it consistently on their machines as well.

Let me try some more may be with different environment. Will let you know.

**Comment by richardpringle** [comment]
@itsJyo... weird. @superkhau, could you try to reproduce this as well? [Here's the repo for reproducing](https://github.com/itsJyo/loopback-sandbox).

**Comment by superkhau** [comment]
node v6.1.0
npm 3.8.6

```
current Context Before Create : Namespace {
  name: 'loopback',
  active: { accessToken: undefined, tenantid: 'ev' },
  _set: [ null ],
  id:
   AsyncListener {
     create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }
current Context after create : Namespace {
  name: 'loopback',
  active: { accessToken: undefined, tenantid: 'ev' },
  _set: [ null ],
  id:
   AsyncListener {
     create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }
current Context Before Rest : Namespace {
  name: 'loopback',
  active: { accessToken: undefined, tenantid: 'ev' },
  _set: [ null ],
  id:
   AsyncListener {
     create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }
{}
current Context After Rest : Namespace {
  name: 'loopback',
  active: null,
  _set: [],
  id:
   AsyncListener {
     create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }
```

**Comment by superkhau** [comment]
node v4.2.4
npm 2.14.12

```
current Context Before Create : Namespace {
  name: 'loopback',
  active: { accessToken: undefined, tenantid: 'ev' },
  _set: [ null ],
  id:
   AsyncListener {
     create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }
current Context after create : Namespace {
  name: 'loopback',
  active: { accessToken: undefined, tenantid: 'ev' },
  _set: [ null ],
  id:
   AsyncListener {
     create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }
current Context Before Rest : Namespace {
  name: 'loopback',
  active: { accessToken: undefined, tenantid: 'ev' },
  _set: [ null ],
  id:
   AsyncListener {
     create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }
{}
current Context After Rest : Namespace {
  name: 'loopback',
  active: null,
  _set: [],
  id:
   AsyncListener {
     create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }
```

**Comment by itsJyo** [comment]
@superkhau ,Thank you for trying to reproduce the issue. The output shows the context.active as null after the rest call which is the issue i was facing. 
@richardpringle Now as the issue could be reproduced it will be helpful to find the cause of the issue.

**Comment by richardpringle** [comment]
@itsJyo, I put a bug label on here so it has been added to the backlog!

Now to figure out what's causing the bug...
