### ISSUE TITLE
Empty path variables and slashes interpretation

### ISSUE THREAD

**Issue by alexxgathp** [strongloop/loopback-connector-rest#61]
Defining the operations path variable does not work as I expected. Empty path variables, that are inputted, are interpreted as {name_of_path_variable} and slashes in the path variable are expected as these characters %2F

datasources.json excerpt

```
 "operations": [
      {
        "template": {
          "method": "GET",
          "url": "http://IP_address/api/{p}"          
          },
        "functions": {
          "find": ["p"]
        }
      }
    ]
```

**Comment by alexxgathp** [comment]
I found a way around the empty issue. If I set the baseURL and then take out a slash in the url like below, then for some reason it does the empty like I thought it should. As for the inputted slashes in the path variable, I guess I will just try out converting the requests to %2F instead. By the way, I am testing with Postman and the Loopback Explorer. Loopback Explorer converts the slashes to %2F automatically. Postman does not. I am betting the browser will be the same as Postman though. I'll post back here if it isn't...

Regarding the empty path variable issue, the reason I want a GET without the path variable is because I can receive certain data from the API without any path variable present.
```
 "baseURL": "http://IP_address/api{p}",
 "operations": [
      {
        "template": {
          "method": "GET",
          "url": "http://IP_address/api{p}"          
          },
        "functions": {
          "find": ["p"]
        }
      }
    ]
```

**Comment by alexxgathp** [comment]
Yes, that essentially describes the use case. Basically, I'm using it as a wildcard GET to another API. It was for testing and development purposes.

I ended up doing the workaround by replacing the necessary slashes in the request with %2F.

**Comment by richardpringle** [comment]
weird... I would think that you shouldn't have to do that though. I'll throw a bug label on here and hopefully someone can come up with a more permanent fix. The fix should be trivial for this use-case but could change the expected behavior for another.
