### ISSUE TITLE
Escape braces in templates

### ISSUE THREAD

**Issue by avinmathew** [strongloop/loopback-connector-rest#63]
I'm trying to call a web service whose param requires a stringifed object, e.g.:

```
{
  "template": {
    "method": "POST",
    "url": "http://example.com",
    "query": {
        "request": "{\"a\":{\"b\":[]},\"c\":0}"
        }
      },
      "functions": {
        "myFunction": []
      }
}
```

`JSONTemplate.prototype.build` transforms the data into `"{\"a\":,\"c\":0}"`. Is there a way to escape braces in a string? Alternatively, is there a way to insert the parameter in a `beforeRemote` hook?

**Comment by 0candy** [comment]
@avinmathew Did you try using the Unicode representation?
`{}`
`\u007B" "\u007D`

**Comment by avinmathew** [comment]
I didn't try it, but my guess seeing that `"\u007B\u007D" === "{}"` evaluates to `true` is that it would probably still not work.

From memory, I got around this issue by setting the args in a `beforeRemote` hook, rather than use the templating feature.
