### ISSUE TITLE
Prevent evaluating of template expressions in a request body.

### ISSUE THREAD

**Issue by rduboveckij** [strongloop/loopback-connector-rest#71]
Reproduce steps:
1) Create loopback connector rest operation.
`
{
  "template": {
    "method": "POST",
    "url": "http://localhost:3000/posts",
    "body": "{!body}"
  },
  "functions": {
    "createPost": ["body"]
  }
}
`
2) Run method with expression inside.
`
Model.createPost({text: "{body}", groups: ["{__proto__}"]})
`
3) Look to response description.
`
RangeError:Maximum call stack size exceeded or
TypeError: Cannot read property 'toLowerCase' of undefined
`
Probaly the problem in https://github.com/strongloop/loopback-connector-rest/blob/master/lib/template.js

One of workaround is validating this case by traverse and initial regexp by string value /{([^{}]+)}/g and throw error 400.

PS: Please fix it, I don't want to use a workaround.

**Comment by RootMale** [comment]
+1
