### ISSUE TITLE
Docs Need An Example passing client id and secret

### ISSUE THREAD

**Issue by orbsi** [strongloop/loopback-connector-rest#81]
The documentation for how to use the loopback connector needs to show how to configure the datasource and model for a REST endpoint that requires an authentication token.

Specifically, how do you configure the datasource to pass in a client id, and client secret to get the authentication token?

How is the authentication token added to the model requests that use the defined REST Datasource?

I found the below json in the loopback-connector-rest test directory.  How would something like this json be setup in the datasource so models that use the rest datasource can pass the access token to methods under "https://example.com/v1/"?
```json
{
  "method": "POST",
  "url": "https://example.com/v1/authenticate",
  "body": {
    "auth_data": {
      "{!uniqueId}": {
        "id": "third_party",
        "emailAddress": "{!email}"
      }
    },
    "grant_type": "client_credentials",
    "client_id": "{!clientId}",
    "client_secret": "{!clientSecret}"
  }
}
```

**Comment by ibm-om** [comment]
Hi Orbsi, I'm with the Docs Team and I'm looking into your helpful suggestion. Thank you!

**Comment by crandmck** [comment]
@gunjpan Can you help with this?

**Comment by gunjpan** [comment]
@crandmck : Sure thing, I'll verify the details on how this works and write it down. Will update you once have something for review. thanks.
