### ISSUE TITLE
Response is always array

### ISSUE THREAD

**Issue by cojack** [strongloop/loopback-connector-rest#82]
Hello,
Please add option to not wrap response to array `rest-builder.js:555` have:
```javascript

        if (jsonPath && self.template.template.responsePath) {
          result = jsonPath({
            wrap: true, // this line
            json: body,
            path: self.template.template.responsePath,
          });
        }
```

so if you will provide an option to not wrap response always to array will be awesome :heart: 

Regards.

**Comment by Amir-61** [comment]
@cojack I suggest that you send a PR with fixes and test cases...
