### ISSUE TITLE
POST operations created on datasource via template does not handle request.body properly

### ISSUE THREAD

**Issue by suryakand** [strongloop/loopback-connector-rest#84]
Consider that an operation->getmyapiresponse is create as follows on a data source  (my-ds). 

```json
"my-ds": {
    "name": "my-ds",
    "baseURL": "http://someapihost.com",
    "crud": false,
    "debug": true,
    "connector": "rest",
    "operations": [
      {
        "template": {
          "method": "POST",
          "url": "http://someapihost.com/myapi",
          "body": {
            "myname": "{!myname:object}"
          }
        },
        "functions": {
          "getmyapiresponse": [
            {
              "name": "myname",
              "type": "object",
              "source": "body"
            }
          ]
        }
      }
    ],
    "options": {
      "headers": {
        "accept": "application/json",
        "content-type": "application/json"
      },
      "strictSSL": false
    }
  }
```

Above definition expects submitted information will be passed to http://someapihost.com/myapi as req.body and there is logic in rest-builder.js to creates final request and seems like the problem is at this line:

```json
 if (json.body !== undefined) {
    req.body =  json.body;
  }
```

json.body above return actual req.body wrapped in another object (in this case req.body.myname) based on template definition ("body" section):

```json  
"body": {
  "**myname**": "{!myname:object}"
}
```

If I change above code logic as follows it works for me as expected:

```json
if (json.body !== undefined) {
    req.body = json.body.myname? json.body.myname : json.body;
  }
```

Seems like the logic to populate the final request in case of POST requests does not reads the submitted request from right place.

**Comment by shenghu** [comment]
I have the same need for rest connector to pipe req of serviceA to serviceB, where serviceB is defined as datasource (rest connector) of serviceA. Is this possible? 

@suryakand did you try to set "body": "{myname}"?
